## SVD vs PCA

Note: PCA and the SVD are the same thing and it's usually better to just use the SVD of the centered data matrix because SVD algorithms are faster and numerically more stable than PCA.

라는 의견이 quora 전문가한테서 달려왔음.

일반적으로는 SVD 가 더 좋다고 함.

https://stats.stackexchange.com/questions/314046/why-does-andrew-ng-prefer-to-use-svd-and-not-eig-of-covariance-matrix-to-do-pca

사실상 둘은 수학적으로는 같은 방식을 차용하나, SVD의 방식이 훨씬 안정적이고, 머신 러닝 분야에서는 SVD를 추천한다고 함


In [1]:
import numpy as np
from numpy.linalg import svd

np.random.seed(21)
a = np.random.randn(4,4)
print(np.round(a,3))

[[-0.052 -0.111  1.042 -1.257]
 [ 0.745 -1.711 -0.206 -0.235]
 [ 1.128 -0.013 -0.613  1.374]
 [ 1.611 -0.689  0.692 -0.448]]


In [2]:
U, Sigma, Vt = svd(a)
print(U.shape,Sigma.shape,Vt.shape)
print(np.round(U,3))
print(np.round(Sigma,3))
print(np.round(Vt,3))

(4, 4) (4,) (4, 4)
[[ 0.13  -0.666  0.236  0.696]
 [ 0.653  0.011 -0.744  0.142]
 [ 0.236  0.734  0.323  0.549]
 [ 0.708 -0.133  0.535 -0.441]]
[2.531 2.367 1.238 0.076]
[[ 0.745 -0.641  0.137 -0.122]
 [ 0.278  0.058 -0.523  0.804]
 [ 0.533  0.706  0.462  0.066]
 [-0.289 -0.296  0.703  0.579]]


In [3]:
Sigma_mat = np.diag(Sigma)
a_ = np.dot(np.dot(U,Sigma_mat),Vt)
print(np.round(a_,3))

[[-0.052 -0.111  1.042 -1.257]
 [ 0.745 -1.711 -0.206 -0.235]
 [ 1.128 -0.013 -0.613  1.374]
 [ 1.611 -0.689  0.692 -0.448]]


In [4]:
a[2] = a[0] + a[1]
a[3] = a[0]
print(np.round(a_,3))

[[-0.052 -0.111  1.042 -1.257]
 [ 0.745 -1.711 -0.206 -0.235]
 [ 1.128 -0.013 -0.613  1.374]
 [ 1.611 -0.689  0.692 -0.448]]


In [5]:
U, Sigma, Vt = svd(a)
print(U.shape,Sigma.shape,Vt.shape)
print(np.round(U,3))
print(np.round(Sigma,3))
print(np.round(Vt,3))

(4, 4) (4,) (4, 4)
[[ 0.372 -0.511  0.772 -0.063]
 [ 0.385  0.672  0.304  0.554]
 [ 0.758  0.161 -0.304 -0.554]
 [ 0.372 -0.511 -0.468  0.617]]
[3.395 2.035 0.    0.   ]
[[ 0.228 -0.625  0.392 -0.635]
 [ 0.327 -0.653 -0.525  0.436]
 [ 0.601  0.389 -0.507 -0.48 ]
 [-0.692 -0.177 -0.56  -0.42 ]]


In [6]:
U_ = U[:,:2]
Sigma_ = np.diag(Sigma[:2])
Vt_ = Vt[:2]
print(U_.shape,Sigma_.shape,Vt_.shape)

a_ = np.dot(np.dot(U,Sigma_mat),Vt)
print(np.round(a_,3))

(4, 2) (2, 2) (2, 4)
[[ 0.397  0.573  0.523 -1.583]
 [ 0.94  -1.51  -0.668 -0.124]
 [ 0.364 -1.587  0.766 -0.854]
 [-0.562 -0.033  1.272 -0.869]]
